web:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./code:/code
        - ./config/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
        - ./config:/config
