web:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./code:/code
        - ./config/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
        - ./config:/config

db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"

debezium:
    image: debezium/connect:1.1
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
    links:
        - db
    ports:
        - "8083:8083"
