web:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./code:/code
        - ./config/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    build: './docker/php'
    volumes:
        - ./code:/code
        - ./config:/config
    links:
        - db

db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
        - ./data:/var/lib/mysql
    ports:
      - "3306:3306"